---
- name: Demo playbook for setting up First EC2 Instance
# 1) Creates a cutome security group
# 2) Spins up new EC2 Instances
# 3) Waits for SSH to become active on Instance 
#
# Version 1.0       Akhil Singh 06/02/2021
#
  hosts: localhost
  tasks:
  - name: Setting up Security/Firewall Group
    ec2_group: 
       name: Akhil_aws_security_grp
       description: Rules allowing Traffic on Port 22 and 80
       region: ap-south-1
       rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
       rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
  - name: Provision a EC2 Instance 
    ec2: 
      key_name: Akhil-AWSKey
      region: ap-south-1
      instance_type: t2.micro
      image: ami-0a9d27a9f4f5c0efc
      wait: yes
      wait_timeout: 500
      count: 1
      instance_tags: 
        name: ansiblenode2
        owner: akhil
      monitoring: no
      vpc_subnet_id: subnet-920b30f6
      assign_public_ip: yes
      group: akhil_aws_security_grp
    register: ec2_out
  - name: wait for ssh to come up
    wait_for: host={{ item.pubic_dns_name }} port=22 delay=60 timeout=320 state=started
    with_items: '{{ec2_out.instances}}'
