---
- name: start the multiple services
  hosts: all
  tasks:
  - name: start the services
    systemd:
     name: "{{ item }}"
     state: started
     enabled: true
    loop: 
      - httpd
      - sshd
      - firewalld
