---
- name: configure the apache server with variables 
  hosts: all
  vars:
   - my_pkg: httpd
   - my_svc: httpd
   - destination: /var/www/html/index.html
   - my_content: "Apache server is using Ansible Variables"
   - rule: httpd
  tasks:
  - name: Installing the pkg
    yum: 
     name: "{{ my_pkg }}"
     state: latest
  - name: start the service 
    systemd:
     name: "{{ my_svc }}"
     state: started
     enabled: true
  - name: copy my content to the destination
    copy:
     content: "{{ my_content }}"
     dest: "{{ destination }}"
  - name: enable the httpd service on firewalld 
    firewalld:
     service: "{{ rule }}"
     immediate: true
     permanent: true
     state: enabled

 
