---
- name: Install the httpd package start the httpd service creating the html page and then enbale the httpd on firewall
  hosts: all
  become: true
  tasks: 
   - name: Install the httpd package
     yum:
      name: httpd
      state: latest
   
   - name: 
     systemd: 
      name: 
        - httpd
        - firewalld
      state: started
      enabled: true
     
   - name:
     copy:
      content: 'This is my testing web server'
      dest: /var/www/html/index.html

   - name: enable the httpd port in firewalld
     firewalld:
      service: http
      state: enabled
      immediate: true
      permanent: true
