---
- name: Install the tomcat server
  hosts: all
  become: true
  vars:
   - tomcat_url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.tar.gz 

  tasks:
  - name: Install java
    yum:
     name: java
     state: latest
  - name: Download the tomcat server packages
    get_url:
     url: "{{ tomcat_url }}"
     dest: /tmp
  - name: extract the tomcat packages
    unarchive:
     src: /tmp/apache-tomcat-8.5.61.tar.gz
     dest: /opt
     remote_src: yes
  - name: start the tomcat service
    shell: nohup /opt/apache-tomcat-8.5.61/bin/startup.sh
