---
- name: ftp configuration 
  hosts: all
  tasks:
   - name: Installing the vsftpd package
     yum: 
      name: vsftpd
      state: latest

   - name: start the vsftpd service 
     systemd:
      name: vsftpd
      state: started
      

